(* -LICENSE-START-
** Copyright (c) 2016 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*)


unit DeckLinkAPI.Discovery;

{$TYPEDADDRESS OFF} // Unit must be compiled without type-checked pointers. 
{$WARN SYMBOL_PLATFORM OFF}
{$WRITEABLECONST ON}
{$VARPROPSETTER ON}
{$ALIGN 4}

interface

uses
  System.SysUtils, System.Variants, Winapi.ActiveX;

const
  IID_IDeckLink: TGUID = '{C418FBDD-0587-48ED-8FE5-640F0A14AF91}';
  
// Type Declarations

// Enumeration Mapping


// Forward Declarations
type
  IDeckLink = interface;

(* Interface IDeckLink - represents a DeckLink device *)
// *********************************************************************//
// Interface: IDeckLink
// Flags:     (0)
// GUID:      {C418FBDD-0587-48ED-8FE5-640F0A14AF91}
// *********************************************************************//
  IDeckLink = interface(IUnknown)
    ['{C418FBDD-0587-48ED-8FE5-640F0A14AF91}']
    function GetModelName(out modelName: WideString): HResult; stdcall;
    function GetDisplayName(out displayName: WideString): HResult; stdcall;
  end;

(* Coclasses *)

implementation

end.


